### PR TITLE
Filter figma ids

### PR DESCRIPTION
**Pull request by GaspardC**
To test → 
http://localhost:3000/#/figma?bytesimBucket=bytesim-bucket&region=eu-west-3&key=1350067722696166.5_bytesimname_bytesim_dev___Page_1.svg&new=true

Screenshot 2022-11-28 at 16 02 49

### CODE REVIEW

**Comment by GaspardC** [comment]
The zones and children of the hidden zones will be deleted - a new store will be created without them
the modal appears when the params new=true is in the URL (generated by the Figma plugin)

**Comment by slecorne** [comment]
@GaspardC initialization si pretty slow with some more complex structures. Could you check with localhost:3000/#/figma?bytesimBucket=bytesim&region=eu-central-1&key=337167135298713_bytesimname_ByteSim___Design.svg&new=true
if you can optimize some parts more. And also add a more visible spinner when loading the page during parsing

**Comment by GaspardC** [comment]
> @GaspardC functionality is great but initialization is pretty slow with some more complex structures. Could you check with localhost:3000/#/figma?bytesimBucket=bytesim&region=eu-central-1&key=337167135298713_bytesimname_ByteSim___Design.svg&new=true if you can optimize some parts more. And also add a more visible spinner when loading the page during parsing

@slecorne I made an update, 
I added some spinner and slightly delayed the zone tree rendering to prevent lagging effects

tell me if it's ok for you :)

**Comment by slecorne** [comment]
> > @GaspardC functionality is great but initialization is pretty slow with some more complex structures. Could you check with localhost:3000/#/figma?bytesimBucket=bytesim&region=eu-central-1&key=337167135298713_bytesimname_ByteSim___Design.svg&new=true if you can optimize some parts more. And also add a more visible spinner when loading the page during parsing
> 
> @slecorne I made an update, I added some spinners and slightly delayed the zone tree rendering to prevent lagging effects
> 
> tell me if it's ok for you :)

thanks, much better with the spinner. It was still pretty slow on my example. I adapted the code to not load the zone form in case of SVG modal import, that was the slow part. Could you check my latest commit to see if all ok for you?

**Comment by GaspardC** [comment]
> > > @GaspardC functionality is great but initialization is pretty slow with some more complex structures. Could you check with localhost:3000/#/figma?bytesimBucket=bytesim&region=eu-central-1&key=337167135298713_bytesimname_ByteSim___Design.svg&new=true if you can optimize some parts more. And also add a more visible spinner when loading the page during parsing
> > 
> > 
> > @slecorne I made an update, I added some spinners and slightly delayed the zone tree rendering to prevent lagging effects
> > tell me if it's ok for you :)
> 
> thanks, much better with the spinner. It was still pretty slow on my example. I adapted the code to not load the zone form in case of SVG modal import, that was the slow part. Could you check my latest commit to see if all ok for you?

perfect 👌

**Pull request merged**
